import Head from 'next/head'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Himanshu website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Himanshu website <a href='./about' target="_blank">:)</a>
        </h1>
        <hr />
        <hr />
        <img className={styles.MainImg} src="http://cdn.mos.cms.futurecdn.net/WqzWxn2pBqvPN9n4DBrjr5.jpg" alt="blog website photo"  width={300} height={200} />
        <div className={styles.blogpost}>
          <div className={styles.blog}>
            <h1>Blog posts </h1>
            <p>hey this is the new blog where people add there content</p>
          </div>
          <div className={styles.blog}>
            <h1>Blog posts </h1>
            <p>hey this is the new blog where people add there content</p>
          </div>
          <div className={styles.blog}>
            <h1>Blog posts </h1>
            <p>hey this is the new blog where people add there content</p>
          </div>
        </div>
      </main>


    </div>
  )
}
